import React, {useState} from "react";
import {Popover, Tabs, Tooltip} from "antd";
import {
  SmileOutlined,
  HeartOutlined,
  StarOutlined,
  CoffeeOutlined,
  TrophyOutlined,
  CarOutlined,
  BulbOutlined,
  FlagOutlined,
} from "@ant-design/icons";

interface EmojiPickerProps {
  onSelectEmoji?: (emoji: string) => void;
}

interface EmojiCategory {
  key: string;
  label: string;
  icon: React.ReactNode;
  emojis: string[];
}

const emojiCategories: EmojiCategory[] = [
  {
    key: "faces",
    label: "Mặt cười & hình người",
    icon: <SmileOutlined/>,
    emojis: [
      "😀",
      "😃",
      "😄",
      "😁",
      "😅",
      "😂",
      "🤣",
      "😊",
      "😇",
      "🙂",
      "🙃",
      "😉",
      "😌",
      "😍",
      "🥰",
      "😘",
      "😗",
      "😙",
      "😚",
      "😋",
      "😛",
      "😝",
      "😜",
      "🤪",
      "🤨",
      "🧐",
      "🤓",
      "😎",
      "🤩",
      "🥳",
      "😏",
      "😒",
      "😞",
      "😔",
      "😟",
      "😕",
      "🙁",
      "☹️",
      "😣",
      "😖",
      "😫",
      "😩",
      "🥺",
      "😢",
      "😭",
      "😤",
      "😠",
      "😡",
      "🤬",
      "🤯",
      "😳",
      "🥵",
      "🥶",
      "😱",
      "😨",
      "😰",
      "😥",
      "😓",
      "🤗",
      "🤔",
    ],
  },
  {
    key: "animals",
    label: "Động vật & thiên nhiên",
    icon: <HeartOutlined/>,
    emojis: [
      "🐶",
      "🐱",
      "🐭",
      "🐹",
      "🐰",
      "🦊",
      "🐻",
      "🐼",
      "🐨",
      "🐯",
      "🦁",
      "🐮",
      "🐷",
      "🐸",
      "🐵",
      "🐔",
      "🐧",
      "🐦",
      "🐤",
      "🐣",
      "🐥",
      "🦆",
      "🦅",
      "🦉",
      "🦇",
      "🐺",
      "🐗",
      "🐴",
      "🦄",
      "🐝",
      "🐛",
      "🦋",
      "🐌",
      "🐚",
      "🐞",
      "🐜",
      "🕷️",
      "🦂",
      "🦀",
      "🐠",
      "🐟",
      "🐡",
      "🐬",
      "🦈",
      "🐳",
      "🐋",
      "🐊",
      "🐆",
      "🐅",
      "🐃",
      "🐂",
      "🐄",
      "🦌",
      "🐪",
      "🐫",
      "🦒",
      "🦘",
      "🐘",
      "🦏",
      "🦛",
    ],
  },
  {
    key: "food",
    label: "Ẩm thực",
    icon: <CoffeeOutlined/>,
    emojis: [
      "🍎",
      "🍐",
      "🍊",
      "🍋",
      "🍌",
      "🍉",
      "🍇",
      "🍓",
      "🍈",
      "🍒",
      "🍑",
      "🥭",
      "🍍",
      "🥥",
      "🥝",
      "🍅",
      "🍆",
      "🥑",
      "🥦",
      "🥬",
      "🥒",
      "🌶",
      "🌽",
      "🥕",
      "🧄",
      "🧅",
      "🥔",
      "🍠",
      "🥐",
      "🥯",
      "🍞",
      "🥖",
      "🥨",
      "🧀",
      "🥚",
      "🍳",
      "🧈",
      "🥞",
      "🧇",
      "🥓",
      "🥩",
      "🍗",
      "🍖",
      "🦴",
      "🌭",
      "🍔",
      "🍟",
      "🍕",
      "🥪",
      "🥙",
      "🧆",
      "🌮",
      "🌯",
      "🥗",
      "🥘",
      "🥫",
      "🍝",
      "🍜",
      "🍲",
      "🍛",
    ],
  },
  {
    key: "activities",
    label: "Hoạt động",
    icon: <TrophyOutlined/>,
    emojis: [
      "⚽️",
      "🏀",
      "🏈",
      "⚾️",
      "🥎",
      "🎾",
      "🏐",
      "🏉",
      "🥏",
      "🎱",
      "🏓",
      "🏸",
      "🏒",
      "🏑",
      "🥅",
      "🏏",
      "🥃",
      "🏸",
      "🏓",
      "🏒",
      "🏑",
      "🥅",
      "🏏",
      "🥃",
      "🏸",
      "🏓",
      "🏒",
      "🏑",
      "🥅",
      "🏏",
      "🎯",
      "🎲",
      "🎰",
      "🎮",
      "🎳",
      "🎭",
      "🎨",
      "🎪",
      "🎟",
      "🎠",
      "🎡",
      "🎢",
      "💈",
      "🎪",
      "🎭",
      "🎨",
      "🎪",
      "🎟",
      "🎠",
      "🎡",
      "🎢",
      "💈",
      "🎪",
      "🎭",
      "🎨",
      "🎪",
      "🎟",
      "🎠",
      "🎡",
      "🎢",
    ],
  },
  {
    key: "travel",
    label: "Đi lại & địa điểm",
    icon: <CarOutlined/>,
    emojis: [
      "🚗",
      "🚕",
      "🚙",
      "🚌",
      "🚎",
      "🏎",
      "🚓",
      "🚑",
      "🚒",
      "🚐",
      "🚚",
      "🚛",
      "🚜",
      "🦯",
      "🦽",
      "🦼",
      "🛴",
      "🚲",
      "🛵",
      "🏍",
      "🛺",
      "🚨",
      "🚔",
      "🚍",
      "🚘",
      "🚖",
      "🚡",
      "🚠",
      "🚟",
      "🚃",
      "🚋",
      "🚞",
      "🚝",
      "🚄",
      "🚅",
      "🚈",
      "🚂",
      "🚆",
      "🚇",
      "🚊",
      "🚉",
      "✈️",
      "🛫",
      "🛬",
      "🛩",
      "💺",
      "🛰",
      "🚀",
      "🛸",
      "🚁",
      "🛥",
      "⛴",
      "🚢",
      "⚓️",
      "⛽️",
      "🚧",
      "🚦",
      "🚥",
      "🚏",
      "🗺",
    ],
  },
  {
    key: "objects",
    label: "Đồ vật",
    icon: <BulbOutlined/>,
    emojis: [
      "⌚️",
      "📱",
      "📲",
      "💻",
      "⌨️",
      "🖥",
      "🖨",
      "🖱",
      "🖲",
      "🕹",
      "🗜",
      "💽",
      "💾",
      "💿",
      "📀",
      "📼",
      "📷",
      "📸",
      "📹",
      "🎥",
      "📽",
      "🎞",
      "📞",
      "☎️",
      "📟",
      "📠",
      "📺",
      "📻",
      "🎙",
      "🎚",
      "🎛",
      "🧭",
      "⏱",
      "⏲",
      "⏰",
      "🕰",
      "⌛️",
      "⏳",
      "📡",
      "🔋",
      "🔌",
      "💡",
      "🔦",
      "🕯",
      "🪔",
      "🧯",
      "🛢",
      "💸",
      "💵",
      "💴",
      "💶",
      "💷",
      "💰",
      "💳",
      "💎",
      "⚖️",
      "🧰",
      "🔧",
      "🔨",
      "⚒",
    ],
  },
  {
    key: "symbols",
    label: "Biểu tượng",
    icon: <StarOutlined/>,
    emojis: [
      "❤️",
      "🧡",
      "💛",
      "💚",
      "💙",
      "💜",
      "🖤",
      "🤍",
      "🤎",
      "💔",
      "❣️",
      "💕",
      "💞",
      "💓",
      "💗",
      "💖",
      "💘",
      "💝",
      "💟",
      "☮️",
      "✝️",
      "☪️",
      "🕉",
      "☸️",
      "✡️",
      "🔯",
      "🕎",
      "☯️",
      "☦️",
      "🛐",
      "⛎",
      "♈️",
      "♉️",
      "♊️",
      "♋️",
      "♌️",
      "♍️",
      "♎️",
      "♏️",
      "♐️",
      "♑️",
      "♒️",
      "♓️",
      "🆔",
      "⚛️",
      "🉑",
      "☢️",
      "☣️",
      "📴",
      "📳",
      "🈶",
      "🈚️",
      "🈸",
      "🈺",
      "🈷️",
      "✴️",
      "🆚",
      "💮",
      "🉐",
      "㊙️",
    ],
  },
  {
    key: "flags",
    label: "Cờ",
    icon: <FlagOutlined/>,
    emojis: [
      "🏳️",
      "🏴",
      "🏁",
      "🚩",
      "🏳️‍🌈",
      "🏳️‍⚧️",
      "🏴‍☠️",
      "🇦🇫",
      "🇦🇽",
      "🇦🇱",
      "🇩🇿",
      "🇦🇸",
      "🇦🇩",
      "🇦🇴",
      "🇦🇮",
      "🇦🇶",
      "🇦🇬",
      "🇦🇷",
      "🇦🇲",
      "🇦🇼",
      "🇦🇺",
      "🇦🇹",
      "🇧🇪",
      "🇧🇷",
      "🇨🇦",
      "🇨🇳",
      "🇩🇰",
      "🇪🇬",
      "🇫🇮",
      "🇫🇷",
      "🇩🇪",
      "🇬🇷",
      "🇮🇳",
      "🇮🇩",
      "🇮🇪",
      "🇮🇱",
      "🇮🇹",
      "🇯🇵",
      "🇰🇷",
      "🇲🇽",
      "🇳🇱",
      "🇳🇿",
      "🇳🇴",
      "🇵🇱",
      "🇵🇹",
      "🇷🇺",
      "🇸🇦",
      "🇸🇪",
      "🇨🇭",
      "🇹🇷",
      "🇬🇧",
      "🇺🇸",
      "🇻🇳",
      "🏳️‍🌈",
      "🏳️‍⚧️",
      "🏴‍☠️",
    ],
  },
];

export function EmojiPicker({onSelectEmoji}: EmojiPickerProps) {
  const [activeKey, setActiveKey] = useState("faces");

  const items = emojiCategories.map((category) => ({
    key: category.key,
    label: (
      <Tooltip title={category.label} placement="top">
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            fontSize: "20px",
          }}
        >
          {category.icon}
        </div>
      </Tooltip>
    ),
  }));

  return (
    <Popover
      styles={{
        body: {
          paddingBottom: 0,
          paddingLeft: 0,
          paddingRight: 0,
        }
      }}
      content={
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            width: "320px",
          }}
        >
          <div
            style={{
              width: "100%",
              height: "250px",
              overflowY: "auto",
              display: "grid",
              gridTemplateColumns: "repeat(8, 1fr)",
            }}
          >
            {emojiCategories
              .find((cat) => cat.key === activeKey)
              ?.emojis.map((emoji, index) => (
                <div
                  key={index}
                  onClick={() => onSelectEmoji?.(emoji)}
                  style={{
                    fontSize: "24px",
                    cursor: "pointer",
                    padding: "4px",
                    textAlign: "center",
                    borderRadius: "4px",
                    transition: "background-color 0.2s",
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.backgroundColor = "#f0f0f0";
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.backgroundColor = "transparent";
                  }}
                >
                  {emoji}
                </div>
              ))}
          </div>
          <Tabs
            activeKey={activeKey}
            onChange={setActiveKey}
            items={items}
            tabPosition="bottom"
            style={{
              borderTop: "1px solid #f0f0f0",
            }}
            tabBarStyle={{
              margin: 0,
              marginLeft: '8px',
              marginRight: '8px',
            }}
            tabBarGutter={20}
          />
        </div>
      }
      trigger={onSelectEmoji === undefined ? [] : "click"}
      placement="topLeft"
    >
      < SmileOutlined
        style={
          {
            fontSize: "20px",
            color:
              "#404040",
            cursor:
              "pointer",
          }
        }
      />
    </Popover>
  );
}
